#!/usr/bin/env python3
"""
Scrape each book's A+ content images from its Amazon.com page and write them to
src/data/aplus.ts as  APLUS: Record<slug, string[]>.

A+ content is the author's OWN brand content, so it's fine to show on the site.
Images are hotlinked from Amazon's CDN (same as the covers). Re-run anytime to
refresh; books with no A+ content simply get no entry (the section hides).

  python3 scripts/fetch-aplus.py
"""
import urllib.request, gzip, re, time, json, os, sys

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOOKS = os.path.join(ROOT, "src", "data", "books.ts")
OUT = os.path.join(ROOT, "src", "data", "aplus.ts")

IMG_RE = re.compile(r'https://m\.media-amazon\.com/images/S/aplus-media/[^"\s\\]+\.(?:png|jpg)')
ID_RE = re.compile(r'/([0-9a-f-]{36})\.')


def fetch(asin: str) -> str:
    # retry on short/bot-walled responses
    for attempt in range(3):
        req = urllib.request.Request(
            f"https://www.amazon.com/dp/{asin}",
            headers={"User-Agent": UA, "Accept-Language": "en-US,en;q=0.9",
                     "Accept-Encoding": "gzip, deflate"})
        with urllib.request.urlopen(req, timeout=25) as r:
            d = r.read()
            if r.headers.get("Content-Encoding") == "gzip":
                d = gzip.decompress(d)
            html = d.decode("utf-8", "ignore")
        if len(html) > 80000 and "automated access" not in html.lower():
            return html
        time.sleep(3 + attempt * 3)
    return html


def aplus_images(html: str):
    """Unique A+ image URLs, in first-seen order, deduped by image id, upsized."""
    out, seen = [], set()
    for u in IMG_RE.findall(html):
        if "pixel" in u:
            continue
        m = ID_RE.search(u)
        key = m.group(1) if m else u
        if key in seen:
            continue
        seen.add(key)
        # request a larger render than the tiny module thumbnails
        u = re.sub(r'_SX\d+_', '_SX600_', u)
        out.append(u)
    return out


def load_existing() -> dict:
    if not os.path.exists(OUT):
        return {}
    cur = open(OUT).read()
    return {
        m.group(1): json.loads(m.group(2))
        for m in re.finditer(r'"([^"]+)":\s*(\[[^\]]*\])', cur)
    }


def main():
    src = open(BOOKS).read()
    # slug + its defaultAsin, in catalogue order
    pairs = re.findall(r'slug:\s*"([^"]+)",.*?defaultAsin:\s*"([^"]+)"', src, re.S)
    # Merge with what we already have: a re-run only ADDS coverage, never wipes
    # books that fail this time (bot wall / lazy-loaded A+).
    result = load_existing()
    print(f"Scanning A+ for {len(pairs)} books (have {len(result)} already)…")
    for i, (slug, asin) in enumerate(pairs, 1):
        try:
            imgs = aplus_images(fetch(asin))
        except Exception as e:
            imgs = []
            print(f"  [{i}/{len(pairs)}] {slug}: ERR {e}")
            time.sleep(2)
            continue
        if imgs:
            result[slug] = imgs
        print(f"  [{i}/{len(pairs)}] {slug}: {len(imgs)} A+ images")
        time.sleep(1.4)

    # write in catalogue order, only books that have images
    ordered = {s: result[s] for s, _ in pairs if result.get(s)}
    body = ",\n".join(
        f'  {json.dumps(s)}: {json.dumps(v, ensure_ascii=False)}'
        for s, v in ordered.items()
    )
    ts = (
        "/**\n"
        " * A+ content images per book (hotlinked from Amazon's CDN). Generated by\n"
        " * scripts/fetch-aplus.py — re-run to refresh. Books with no A+ content are\n"
        " * absent here, so the 'More about this book' section just hides for them.\n"
        " */\n"
        "export const APLUS: Record<string, string[]> = {\n"
        f"{body}\n"
        "};\n\n"
        "export function getAplus(slug: string): string[] {\n"
        "  return APLUS[slug] ?? [];\n"
        "}\n"
    )
    open(OUT, "w").write(ts)
    print(f"\nWrote {OUT}: {len(ordered)}/{len(pairs)} books have A+ images")


if __name__ == "__main__":
    sys.exit(main())
